trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'
  
variables:
  buildconfiguration: 'release'

Steps:
- script: dotnet test 
  displayName: Run unit test

- script: dotnet build --configuration $(buildconfiguration)
  displayName: Build application
  
- script: docker build -t my-image:v1.0.
  displayName: Build image

- script: docker push my-image:v1.0.
  displayName: push image
